---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 22.02.2020 19:51
---
function StartMainTheme()
	--print("играй музыка1")
	TimerStart(CreateTimer(), 1, false, function()
		--print("играй музыка2")
		--PlayThematicMusicBJ("NewMusic/Brandberg - Anubis.mp3;NewMusic/Deficio - Egyptica.mp3")
		--PlayMusicBJ("NewMusic/Brandberg - Anubis.mp3;NewMusic/Deficio - Egyptica.mp3")
		--PlayThematicMusicBJ("NewMusic/Deficio - Egyptica.mp3")--работает
	end)
end
