---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 22.02.2020 18:00
---
function RegisterAnyCheckpointSave()
	SetMaxCheckpointSaves(3)
	local gg_trg_RANGE = CreateTrigger()
	local e
	local k=0
	local id=FourCC('o000')--верфь
	GroupEnumUnitsInRect(perebor,bj_mapInitialPlayableArea,nil)
	while true do
		e = FirstOfGroup(perebor)
		if e == nil then break end
		if UnitAlive(e) and GetUnitTypeId(e)==id then
			k=k+1

			TriggerRegisterUnitInRangeSimple(gg_trg_RANGE, 256, e)
		end
		GroupRemoveUnit(perebor,e)
	end

	TriggerAddAction(gg_trg_RANGE, function()
		local hero=GetTriggerUnit()
		local x,y=GetUnitXY(hero)
		local e
		local id=FourCC('o000')--верфь
		local data=HERO[UnitGetPid(hero)]
		--print(GetUnitName(hero).." 1")
		HealUnit(hero,9999)
		GroupEnumUnitsInRange(perebor,x,y,500,nil)
		while true do
			e = FirstOfGroup(perebor)
			if e == nil then break end
			if UnitAlive(e) and GetUnitTypeId(e)==id and data.ChkPointID~=GetHandleId(e) then  --
				local pid=GetPlayerId(GetOwningPlayer(hero))
				SetUnitOwner(e,GetOwningPlayer(hero),true)
				SaveGameCheckpoint("Ship",true)
				data.ChkPointID=GetHandleId(e)
				--print(GetUnitName(hero))
				DefineStartLocation(0, x, y)
				SetPlayerStartLocation(GetOwningPlayer(hero),0)

				--добавляем, чуть чуть чуть боеприпасов для каждого разблокированного оружия
				if GetOwningPlayer(e)~=GetOwningPlayer(hero) then
					if Ammo[pid].Available.Single then
						HeroUpdateWeaponCharges(hero,1,-50)
					end
					if Ammo[pid].Available.Board then
						HeroUpdateWeaponCharges(hero,2,-50)
					end
					if Ammo[pid].Available.Rocket then
						HeroUpdateWeaponCharges(hero,3,-10)
					end
					if Ammo[pid].Available.Fire then
						HeroUpdateWeaponCharges(hero,4,-100)
					end
					if Ammo[pid].Available.Toss then
						HeroUpdateWeaponCharges(hero,5,-5)
					end
					if Ammo[pid].Available.Barrel then
						HeroUpdateWeaponCharges(hero,6,-5)
					end
					if Ammo[pid].Available.Light then
						HeroUpdateWeaponCharges(hero,7,-10)
					end
					if Ammo[pid].Available.Saw then
						--HeroUpdateWeaponCharges(hero,2,-10)
						--ничего, это оружие бесконечное
					end
					if Ammo[pid].Available.Oil then
						HeroUpdateWeaponCharges(hero,9,-10)
					end
				end
			end
			GroupRemoveUnit(perebor,e)
		end
	end)
end

function HealUnit(hero,amount)
	local p=GetOwningPlayer(hero)
	local MaxHP=BlzGetUnitMaxHP(hero)
	local CurrentHP=GetUnitState(hero,UNIT_STATE_LIFE)
	local LoosingHP=MaxHP-CurrentHP
	local OverHeal=amount-LoosingHP
	local TotalHeal=amount
	if LoosingHP<=amount then TotalHeal=LoosingHP	end
	SetUnitState(hero,UNIT_STATE_LIFE,CurrentHP+TotalHeal)
	if TotalHeal>1 then
		FlyTextTagLumberBounty(hero,"+"..R2I(TotalHeal),p)
	end
	return OverHeal
end