---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 16.02.2020 18:42
---
function InitZone1()
	TimerStart(CreateTimer(), 10, true, function()
		--CreateZombies()
		InitZombies()
		--gg_rct_TestFog

	end)
	--print("0")
	CreateFogInRect(gg_rct_TestFog)
	MineReplacer()
	DeeperShip()
	Kraken=FindUnitOfType(FourCC('n004'))
	BossZoneInit()
	TentacleInFog()
	--Открыть ворота к боссу
end

function CreateFogInRect(rect)
	--print("1")
	local xMax,yMax=GetRectMaxX(rect),GetRectMaxY(rect)
	local xMin,yMin=GetRectMinX(rect),GetRectMinY(rect)
	local step=70
	local Wide=R2I(math.abs(xMax-xMin)/step)
	local Height=R2I(math.abs(yMax-yMin)/step)
	local xPos,yPos=xMax,yMax
	local fog={}
	--print("x="..Wide.." y="..Height)
	for i=0,Wide do
		xPos=MoveX(xMax,-step*i,0)
		--print("Создан туман по х="..i)
		for k=0,Height do
			yPos=MoveY(yMax,-step*k,90)
			--fog[i]=
			--print("Создан туман по y="..k)
			local eff =AddSpecialEffect("bluegas4",xPos,yPos) --WaterOrb --bluegas
			SetEffectAlphaNearHero(eff)
		end
	end
end

function SetEffectAlphaNearHero(eff)
	local x,y=BlzGetLocalSpecialEffectX(eff),BlzGetLocalSpecialEffectY(eff)
	local t=CreateTimer()
	TimerStart(t,0.3, true, function()
		local IsContent, hero=PointContentUnit(x,y,450)

		if IsContent then
			local xh,yh=GetUnitXY(hero)
			local xe,ye=BlzGetLocalSpecialEffectX(eff),BlzGetLocalSpecialEffectY(eff)
			local angle=(AngleBetweenXY(xe,ye,xh,yh)/bj_DEGTORAD)-180
			--EffectAddForce(eff,angle,30,500,t)

			--print(angle)
			BlzSetSpecialEffectAlpha(eff,80)
			--print("alpha")
			BlzPlaySpecialEffect(eff,ANIM_TYPE_DEATH)
			--DestroyEffect(eff)
			--BlzSetSpecialEffectPosition(eff,xn,yn,0)
			--DestroyTimer(GetExpiredTimer())
			--BlzSetSpecialEffectTime(eff,2300)
			--BlzSetSpecialEffectPosition(eff,4000,4000,0)
		else
			BlzSetSpecialEffectAlpha(eff,20)
			BlzPlaySpecialEffect(eff,ANIM_TYPE_STAND)
			--BlzSetSpecialEffectPosition(eff,x,y,0)
		end
		if not eff then
			DestroyTimer(GetExpiredTimer())
			print("ссылка таймера уничтожена")
		end

	end)
end


function EffectAddForce(eff,angle,speed,distance,t)
	local currentdistance=0
	TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
		currentdistance=currentdistance+speed
		local x,y=BlzGetLocalSpecialEffectX(eff),BlzGetLocalSpecialEffectY(eff)
		local newX,newY=MoveX(x,speed,angle),MoveY(y,speed,angle)
		BlzSetSpecialEffectPosition(eff,newX,newY,0)
		--print("forceeff"..currentdistance)
		if currentdistance>=distance   then
			DestroyTimer(GetExpiredTimer())
			DestroyTimer(t)
			DestroyEffect(eff)
		end
	end)
end




function InitZombies()--ужасно, больше так не буду делать, мозголомание бредовое
	local e=nil
	local k=0
	local id=FourCC('n003')
	if OrcSkeletonPool[4]<=OrcSkeletonPool[5]*3 then
		GroupEnumUnitsInRect(perebor,bj_mapInitialPlayableArea,nil)
		while true do
			e = FirstOfGroup(perebor)
			if e == nil then break end
			if UnitAlive(e) and GetUnitTypeId(e)==id then
				local r=GetRandomInt(1,3)
				k=k+1
				if OrcSkeletonPool[5+k]==nil then
					OrcSkeletonPool[5+k]=e
				end

				if OrcSkeletonPool[4]<OrcSkeletonPool[5]*3 then
					if GetUnitUserData(e)<3 then
						local orc=CreateUnit(GetOwningPlayer(e), OrcSkeletonPool[r],GetUnitX(e),GetUnitY(e),0)
						OrcSkeletonPool[4]=OrcSkeletonPool[4]+1
						GroupAddUnit(OrcSkeletonPoolG,orc)
						SetUnitUserData(orc,GetHandleId(e))
						SetUnitUserData(e,GetUnitUserData(e)+1)
						--print("создан скелет"..GetUnitUserData(e))
					end
				else

				end



			end
			GroupRemoveUnit(perebor,e)
		end
		--print("Запущено юнитов: "..k)
		OrcSkeletonPool[5]=k
	end
end

OrcSkeletonPoolG=CreateGroup()
OrcSkeletonPool={
	FourCC('n000'),
	FourCC('n001'),
	FourCC('n002'),
	0,--число скелетов
	4,--число обелисков
	nil,
	nil,
	nil,
	nil,
}
