---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 14.04.2020 1:01
---
function StartAllTorch()
	local e--временный юнит
	local k=0
	local id=FourCC('e006') -- Факел

	GroupEnumUnitsInRect(perebor,bj_mapInitialPlayableArea,nil)
	while true do
		e = FirstOfGroup(perebor)
		if e == nil then break end
		if UnitAlive(e) and GetUnitTypeId(e)==id then
			k=k+1
			local rf=GetRandomReal(-.5,.5)
			local angle=GetUnitFacing(e)
			local torch=e
			TimerStart(CreateTimer(), 2+rf, true, function()
				print("стреляем "..GetUnitName(torch))
				SingleCannon(torch,angle,"Abilities\\Weapons\\FireBallMissile\\FireBallMissile.mdl")
			end)
		end
		GroupRemoveUnit(perebor,e)
	end
	print("Запущено факелов: "..k)
end