---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 13.05.2020 2:16
---

function DontMove()
	local this = CreateTrigger()
	TriggerRegisterAnyUnitEventBJ(this, EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER)
	TriggerRegisterAnyUnitEventBJ(this, EVENT_PLAYER_UNIT_ISSUED_TARGET_ORDER)
	TriggerAddAction(this, function()
		local hero=GetTriggerUnit()
		if GetIssuedOrderIdBJ() == String2OrderIdBJ("move") and IsUnitType(hero, UNIT_TYPE_HERO) then
			local data=HERO[GetPlayerId(GetOwningPlayer(hero))]
			if false and not data.EnterInTurret then
				PauseUnitBJ(true, hero)
				IssueImmediateOrderBJ(hero, "stop")
				PauseUnitBJ(false, hero)
			end
		end
	end)
end