---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 27.03.2020 22:59
---
function AfterAttack(hero, delay)
	TimerStart(CreateTimer(), delay, false, function()
		local x,y=MoveXY(GetUnitX(hero),GetUnitY(hero),70,GetUnitFacing(hero))
		local data=HERO[GetPlayerId(GetOwningPlayer(hero))]

		if UnitDamageArea(hero,BlzGetUnitBaseDamage(hero,0),x,y,70) then
			data.RevoltSec=0
		end

	end)
end