---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 28.03.2020 1:00
---
function RegisterCollision(hero)
	local ThisTrigger = CreateTrigger()
	local IsWork=false
	if  hero then
		IsWork=true
	end
	TriggerRegisterUnitInRangeSimple(ThisTrigger, 80, hero)
	TriggerAddAction(ThisTrigger, function()
		local CollisionUnit=GetTriggerUnit()
		local data=HERO[GetPlayerId(GetOwningPlayer(hero))]
		--hero - юнит к которому подошли
		--print("any reg "..GetUnitName(CollisionUnit))
		--Общее условие
		if UnitAlive(CollisionUnit) then
			if GetUnitTypeId(CollisionUnit)==FourCC('o005') then--тележка
				if GetOwningPlayer(CollisionUnit)==Player(PLAYER_NEUTRAL_PASSIVE) then
					SetUnitOwner(CollisionUnit,GetOwningPlayer(hero),true)
					data.CartUnit=CollisionUnit

				end
			end
			if GetUnitTypeId(CollisionUnit)==FourCC('e007') then--Сфрера огня
				--print("Подобрана сфера огня, учим героя метать фаер болы")
				KillUnit(CollisionUnit)
				if not data.Perk16 then
					data.Perk16=true
					UnitAddAbility(hero,FourCC('A006'))--огонёк
					if GetLocalPlayer()==GetOwningPlayer(hero) then
						BlzFrameSetVisible(PerkIsLock[16],false)
						BlzFrameSetVisible(FrameSelecter[16],true)
					end
				end
			end
			if GetUnitTypeId(CollisionUnit)==FourCC('o001') then--дрова на лесопилке
				local k=1
				if data.Perk1 then
					k=k+1
				end
				if data.IsWood then
					if GetLosingHP(hero)<=5 then-- Техника безопасности
						--print("Полное хп")
						data.TreeCountOnTB=k+data.TreeCountOnTB
						if data.TreeCountOnTB>=10 and not data.Perk10 then
							data.Perk10=true
							if GetLocalPlayer()==GetOwningPlayer(hero) then
								BlzFrameSetVisible(PerkIsLock[10],false)
								BlzFrameSetVisible(FrameSelecter[10],true)
							end
						end
					end
					data.IsWood=false
					--рывок перемещён в другое место в интерфейс

					--print(data.SingleWoodCount)

					HealUnit(hero,1000)
					AddLumber(k,hero)
					MoveWoodAsFarm(hero,k)
					UnitAddItemById(hero,FourCC('I000'))-- ускорение
					data.RevoltSec=0
				end
				if data.CartUnit  and GetUnitUserData(data.CartUnit)>0 then -- дрова из тележки на лесопилке
					local wc=GetUnitUserData(data.CartUnit)
					--k=wc*k
					HealUnit(hero,1000)
					AddLumber(k,hero)
					UnitAddItemById(hero,FourCC('I000'))-- ускорение
					TimerStart(CreateTimer(), 0.1, true, function()
						MoveWoodAsFarm(hero,k)

						data.RevoltSec=0
						SetUnitUserData(data.CartUnit,GetUnitUserData(data.CartUnit)-1)
						SetVisualWood(data.CartUnit,GetUnitUserData(data.CartUnit))
						if GetUnitUserData(data.CartUnit)==0 then
							DestroyTimer(GetExpiredTimer())
						end
					end)
				end
			end
			if GetUnitTypeId(CollisionUnit)==FourCC('e002') then-- дрова у юнита
				if data.CartUnit then
					local wc=GetUnitUserData(data.CartUnit)
					if wc<=5 then
						SetUnitUserData(data.CartUnit,wc+1)
						wc=wc+1
						--print("Всего дерева в тачке="..wc)
						PlaySoundAtPointBJ( gg_snd_Load, 100, RemoveLocation(Location(GetUnitXY(hero))), 0 )
						KillUnit(CollisionUnit)
						SetVisualWood(data.CartUnit,wc)
					end
				else
					if not data.IsWood then
						--print("звук подбора")
						if not data.ReleaseLMB then
							PlaySoundAtPointBJ( gg_snd_Load, 100, RemoveLocation(Location(GetUnitXY(hero))), 0 )
							KillUnit(CollisionUnit)
							data.IsWood=true
						end
					end
				end




			end
			if GetUnitTypeId(CollisionUnit)==FourCC('n001') then -- овца
					data.SheepCount=data.SheepCount+1
					if data.SheepCount==20 then
						data.Perk15=true
						UnitAddAbility(hero,FourCC('A00J'))
						if GetLocalPlayer()==GetOwningPlayer(hero) then
							BlzFrameSetVisible(PerkIsLock[15],false)
							BlzFrameSetVisible(FrameSelecter[15],true)
						end
					end


				SetUnitExploded(CollisionUnit,true)
				local nx,ny=GetUnitXY(CollisionUnit)
				UnitDamageArea(CollisionUnit,100,nx,ny,150)
				DestroyEffect(AddSpecialEffect("Abilities\\Weapons\\Mortar\\MortarMissile",nx,ny))
				KillUnit(CollisionUnit)
				local data=AnyData[GetHandleId(CollisionUnit)]
				local x,y=data.x,data.y
				TimerStart(CreateTimer(), 30, false, function()
					local new =CreateUnit(Player(PLAYER_NEUTRAL_AGGRESSIVE), FourCC('n001'), x, y, 0)
					AnyData[GetHandleId(new)]={
						x=x,
						y=y,
					}
				end)
			end

		end

	end)
	return IsWork
end

function AddLumber (ttk,caster)
	local data=HERO[GetPlayerId(GetOwningPlayer(caster))]
	local ownplayer=GetOwningPlayer(caster)

	data.SingleWoodCount=data.SingleWoodCount+ttk
	if data.SingleWoodCount>=25  and not data.Perk1 then
		data.Perk1=true
		if GetLocalPlayer()==ownplayer then
			BlzFrameSetVisible(PerkIsLock[1],false)
			BlzFrameSetVisible(FrameSelecter[1],true)
		end
	end

	if ttk>0 and data.IsWood then
		FlyTextTagLumberBounty(caster,"+"..ttk,ownplayer)
		AdjustPlayerStateBJ(ttk, ownplayer, PLAYER_STATE_RESOURCE_LUMBER )

		--print("Опыт добавлен")
	end
end

function SetVisualWood(CartUnit,wc)
	UnitRemoveAbility(CartUnit,FourCC('A008'))--1
	UnitRemoveAbility(CartUnit,FourCC('A009'))--2
	UnitRemoveAbility(CartUnit,FourCC('A00A'))--3
	UnitRemoveAbility(CartUnit,FourCC('A00B'))--4
	UnitRemoveAbility(CartUnit,FourCC('A00C'))--5
	UnitRemoveAbility(CartUnit,FourCC('A00D'))--6
	if wc==1 then
		UnitAddAbility(CartUnit,FourCC('A008'))--1
	elseif wc==2  then
		UnitAddAbility(CartUnit,FourCC('A008'))--1
		UnitAddAbility(CartUnit,FourCC('A009'))--2
	elseif wc==3  then
		UnitAddAbility(CartUnit,FourCC('A008'))--1
		UnitAddAbility(CartUnit,FourCC('A009'))--2
		UnitAddAbility(CartUnit,FourCC('A00A'))--3
	elseif wc==4  then
		UnitAddAbility(CartUnit,FourCC('A008'))--1
		UnitAddAbility(CartUnit,FourCC('A009'))--2
		UnitAddAbility(CartUnit,FourCC('A00A'))--3
		UnitAddAbility(CartUnit,FourCC('A00B'))--4
	elseif wc==5  then
		UnitAddAbility(CartUnit,FourCC('A008'))--1
		UnitAddAbility(CartUnit,FourCC('A009'))--2
		UnitAddAbility(CartUnit,FourCC('A00A'))--3
		UnitAddAbility(CartUnit,FourCC('A00B'))--4
		UnitAddAbility(CartUnit,FourCC('A00C'))--5
	elseif wc==6  then
		UnitAddAbility(CartUnit,FourCC('A008'))--1
		UnitAddAbility(CartUnit,FourCC('A009'))--2
		UnitAddAbility(CartUnit,FourCC('A00A'))--3
		UnitAddAbility(CartUnit,FourCC('A00B'))--4
		UnitAddAbility(CartUnit,FourCC('A00C'))--5
		UnitAddAbility(CartUnit,FourCC('A00D'))--6
	end
end