---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 28.03.2020 1:00
---
function RegisterCollision(hero)
	local ThisTrigger = CreateTrigger()
	local IsWork=false
	if  hero then
		IsWork=true
	end
	TriggerRegisterUnitInRangeSimple(ThisTrigger, 80, hero)
	TriggerAddAction(ThisTrigger, function()
		local CollisionUnit=GetTriggerUnit()
		local data=HERO[GetPlayerId(GetOwningPlayer(hero))]
		--hero - юнит к которому подошли
		--print("any reg "..GetUnitName(CollisionUnit))
		--Общее условие
		if UnitAlive(CollisionUnit) then
			if GetUnitTypeId(CollisionUnit)==FourCC('o001') then
				if data.IsWood then
					AddLumber(1,hero)
				end
			end
			if GetUnitTypeId(CollisionUnit)==FourCC('e002') then

				if not data.IsWood then
					print("звук подбора")
					KillUnit(CollisionUnit)
					data.IsWood=true
				end
			end
			if GetUnitTypeId(CollisionUnit)==FourCC('n001') then
				SetUnitExploded(CollisionUnit,true)
				local x,y=GetUnitXY(CollisionUnit)
				UnitDamageArea(CollisionUnit,100,x,y,150)
				DestroyEffect(AddSpecialEffect("Abilities\\Weapons\\Mortar\\MortarMissile",x,y))
				KillUnit(CollisionUnit)
			end

		end

	end)
	return IsWork
end

function AddLumber (ttk,caster)
	local data=HERO[GetPlayerId(GetOwningPlayer(caster))]
	local ownplayer=GetOwningPlayer(caster)
	if ttk>0 and data.IsWood then
		FlyTextTagLumberBounty(caster,"+"..ttk,ownplayer)
		AdjustPlayerStateBJ(ttk, ownplayer, PLAYER_STATE_RESOURCE_LUMBER )
		data.IsWood=false
	end
end