---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 28.03.2020 2:06
CurrentWave=0
function NextWave()
	CurrentWave=CurrentWave+1
	if CurrentWave==1 then

	elseif CurrentWave==2  then

	end
end
