---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 07.03.2020 0:35
---

function TorrentReplacer()
	local e=nil
	local k=0
	local id=FourCC('e00C')--!!!!!--Глифы торрентовdddc
		GroupEnumUnitsInRect(perebor,bj_mapInitialPlayableArea,nil)
		while true do
			e = FirstOfGroup(perebor)
			if e == nil then break end
			if UnitAlive(e) and GetUnitTypeId(e)==id then
				local x,y=GetUnitXY(e)
				KillUnit(e)
				k=k+1
				CreateWhirlpool(x,y)
			end
			GroupRemoveUnit(perebor,e)
		end
		--print("Заменено существ: "..k)
end

function CreateWhirlpool(x,y)
	local eff =AddSpecialEffect("Whirlpool",x,y)
	BlzSetSpecialEffectZ(eff,-190)
	BlzPlaySpecialEffect(eff,ANIM_TYPE_BIRTH)
	TimerStart(CreateTimer(), 5, true, function()
		CreateTorrent(x,y,4,500)
	end)
end
