---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 09.05.2020 23:14
---

function AutoCollectLumber(period)
	local Mill=FindUnitOfType(FourCC('o001'))

	TimerStart(CreateTimer(), period, true, function()
		for i = 0, 3 do
			local data=HERO[i]
			local hero = data.UnitHero
			if IsUnitInRange(hero, Mill, 100) then

				local k=1
				if data.Perk1 then
					k=k+1
				end
				if data.IsWood then
					--print("Автосбор древисины")
					if GetLosingHP(hero)<=5 and not data.Perk10 then-- Техника безопасности
						--print("Полное хп")
						data.TreeCountOnTB=k+data.TreeCountOnTB
						if data.TreeCountOnTB>=10 and not data.Perk10 then
							data.Perk10=true
							PerkUnlocker(data,10)
						end
					end
					data.IsWood=false
					--рывок перемещён в другое место в интерфейс
					data.SingleWoodCount=data.SingleWoodCount+k
					FrameBigSize(data.SelfFrame[1],0.2,1)
					--print("дерево в личном зачете "..data.SingleWoodCount)
					if data.SingleWoodCount>=25  and not data.Perk1 then -- Перкс работник месяца
						data.Perk1=true
						PerkUnlocker(data,1)
					end
					--print(data.SingleWoodCount)

					HealUnit(hero,1000)
					AddLumber(k,hero)
					MoveWoodAsFarm(hero,k)
					UnitAddItemById(hero,FourCC('I000'))-- ускорение
					data.RevoltSec=0
				end
			end
		end

		if not UnitAlive(Mill) then
			DestroyTimer(GetExpiredTimer())
		end
	end)
end