---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 24.04.2020 22:53

function FarmOfPig()
	local farm=FindUnitOfType(FourCC('npgf'))
	local x,y=GetUnitXY(farm)
	local mf=0
	TimerStart(CreateTimer(), 30, true, function()
		local new=CreateUnit(Player(5),FourCC('n007'),x,y,180)
		mf=mf+5
		local hp=200+mf
		BlzSetUnitMaxHP(new,hp)
		HealUnit(new,hp)
	end)
end