---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 17.05.2020 22:30
---

function AnyHPEARandomBuild(x, y)
	AdjustPlayerStateBJ(1000, Player(10), PLAYER_STATE_RESOURCE_LUMBER)
	AdjustPlayerStateBJ(1000, Player(10), PLAYER_STATE_RESOURCE_GOLD)
	for i = 1, 5 do
		local r = GetRandomInt(-800, 800)
		local builder = FindUnitOfType(FourCC('hpea'), 2500, x, y)
		if i == 1 then
			r=0
		end
		if IssueBuildOrderById(builder, FourCC("hwtw"), x + r, y + r) then
			--print("Иду строить")
			IssueImmediateOrder(builder, "repairon")
		else
			IssueImmediateOrder(builder, "autoharvestlumber")
			--print("Не могу построить")
		end
		TimerStart(CreateTimer(), 2, true, function()
			--print(OrderId2String(GetUnitCurrentOrder(builder)))
			if OrderId2String(GetUnitCurrentOrder(builder))=="harvest" then
				IssueImmediateOrder(builder, "autoharvestlumber")
				DestroyTimer(GetExpiredTimer())
			end
		end)
	end
end