---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 28.03.2020 2:06

function InitAllZones()
	EntInTrees()-- превращаем энтов в деревья
	StartAllSaw() -- зона пил
	TimerStart(CreateTimer(), 120, false, function()
		WaveAttack(60)-- волны
	end)
	SetSheepPoint()-- овцы
	StartWinter()--ветер
	CreateVulkano(913,-2550)--вулкан
	StartAllTorch()--фонарики
	FarmOfPig()
	--Normadia()--Высадка пехотинцев
end