---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 08.04.2020 17:34
---
function StartWinter()
	local x,y=2236,-1112--0,0--
	local caster=CreateUnit(Player(10),DummyID,x,y,180)
	UnitAddAbility(caster,FourCC('A005'))
	--local nx,ny=MoveXY(x,y)
	Cast(caster,x-100,y)
	--SetUnitX(caster,3400)
	--SetUnitY(caster,-1200)
end