---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 02.05.2020 2:43
---

function StartTinyAI(xs,ys)
	local boss=FindUnitOfType(FourCC('e009') )
	local stoneEffModel="Abilities\\Weapons\\RockBoltMissile\\RockBoltMissile"
	local Special="Abilities\\Weapons\\ProcMissile\\ProcMissile"

	UnitAddAbility(boss,FourCC('Abun'))
	SetUnitPosition(boss,1420,2597)
	SetUnitOwner(boss,Player(10),true)
	local range=1000
	local x,y=GetUnitXY(boss)
	SetRect(GlobalRect, x - range, y - range, x + range, y +range)
	EnumDestructablesInRect(GlobalRect,nil,function ()
		local d=GetEnumDestructable()
		local dx,dy=GetDestructableX(d),GetDestructableY(d)
		if IsUnitInRangeXY(boss,dx,dy,range) then
			KillDestructable(d)
			--print("очистка зоны")
		end
	end)

	--перенос героев в случайную точку
	for i=0,3 do
		local hero=HERO[i].UnitHero
		if IsUnitInRangeXY(hero,xs,ys,300) then
			--print("герои перенесены")
			SetUnitPosition(hero,1420+GetRandomInt(-1,1)*600,2597+GetRandomInt(-1,1)*600)
		end
	end


	local FW=CreateFogModifierRectBJ(false, Player(0), FOG_OF_WAR_VISIBLE, GlobalRect)
	FogModifierStart(FW)


	--print("создаём каменный круг")

	for i=0,36 do
		local angle=10
		local dx,dy=MoveXY(x,y,range*.8,angle*i)
		local newd=CreateDestructable(FourCC('LTrc'),dx,dy,0,GetRandomInt(1,1),GetRandomInt(1,5))
		SetDestructableInvulnerable(newd,true)
		--print("создан элемент "..i)
	end


	local phase=0
	local sec=0
	TimerStart(CreateTimer(), 1, true, function()
		sec=sec+1
		if sec>=10 then
			sec=0
			phase=phase+1
			print("phase "..phase)
			if phase>=4 then
				phase=0
			end
		end



		if not UnitAlive(boss) then
			DestroyTimer(GetExpiredTimer())
		end
	end)

end