---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 19.05.2020 19:21
---
--stoneEffModel = "Abilities\\Weapons\\RockBoltMissile\\RockBoltMissile"
--Special = "Abilities\\Weapons\\ProcMissile\\ProcMissile"

function InitTurtleZone()
	local this = CreateTrigger()
	TriggerRegisterEnterRectSimple(this, gg_rct_TurtleZone)
	TriggerAddAction(this, function()
		local hero=GetTriggerUnit()
		if IsUnitType(hero,UNIT_TYPE_HERO) then
			StartTurtleAI()
			DisableTrigger(this)
		end
	end)
end




function StartTurtleAI()
	local boss = FindUnitOfType(FourCC('n00D'))
	local BossFight=true
	print("Запущен ИИ черепахи")

	local FW = CreateFogModifierRectBJ(false, Player(0), FOG_OF_WAR_VISIBLE, gg_rct_TurtleZone) --Рект черепахи
	FogModifierStart(FW)

	local phase = 2 --стартовая фаза
	local sec = 0
	local PhaseOn = true
	local OnAttack=true
	TimerStart(CreateTimer(), 1, true, function() --каждую секунду
		local x, y = GetUnitXY(boss)
		if not UnitAlive(boss) then-- Место где босс умер тиник
			StartSound(bj_questCompletedSound)
			DestroyTimer(GetExpiredTimer())
			phase = 0
			--print("Даём нарграду")
			for _=1,14 do
				local r=GetRandomInt(-100,100)
				local r2=GetRandomInt(-100,100)
				CreateFreeWood(x+r,y+r2)
			end
		else --Проверяем есть ли живые герои, когда тиник жив
			if BossFight then
				local k=0
				for i = 0, 3 do
					local hero = HERO[i].UnitHero
					if IsUnitInRange(hero, boss, 3000) then
						k=k+1
					end

					--print("Отталкивание для особо умных")
				end
				if k==0 then
					BossFight=false
					phase=0
					DestroyFogModifier(FW)
					print("Все герои мертвы остановка фаз")
				end
			end
		end
		if BossFight then -- если идёт бой
			sec = sec + 1
			if sec >= 10 then
				sec = 0
				phase = phase + 1
				PhaseOn = true
				--print("phase " .. phase)
				if phase >= 4 then
					phase = 0
				end
			end
			--фазы
			if phase == 1 and PhaseOn then
				PhaseOn = false
				--print("стреляем камнями")

			end
			if phase == 2 and PhaseOn then
				PhaseOn = false
				--print("Падающие камни")

			end
			if phase == 3 and PhaseOn  then -- оживление големов
				PhaseOn = false

			end

		else-- перезапуск боссфайта
			local k=0
			for i = 0, 3 do
				local hero = HERO[i].UnitHero
				if IsUnitInRange(hero, boss, 300) then
					k=k+1
				end
			end
			if k>=1 then
				print("перезапуск боссфайта")
				BossFight=true
			end
		end--конец
	end)
end