---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 11.05.2020 14:19
---

function StartZombies()
	local sPozX={9795,9660,9794,9989}
	local sPozY={4379,3307,2302,1426}
	local xEnd=12000
	local id={FourCC('n009'),FourCC('n00B'),FourCC('n00A')}
	AllZombiesCount=CreateGroup()
	TimerStart(CreateTimer(), 1, true, function()
		local rPoz=GetRandomInt(3,#sPozX)
		local inCave=false
		for i=0,3 do
			if IsUnitInRangeXY(HERO[i].UnitHero,sPozX[rPoz],sPozY[rPoz],1800) then
				inCave=true
			end
		end
		if inCave then
			local new=CreateUnit(Player(14),id[GetRandomInt(1,3)],sPozX[rPoz],sPozY[rPoz],0)
			GroupAddUnit(AllZombiesCount,new)
			SetUnitMoveSpeed(new,100)
			IssuePointOrder(new,"attack",xEnd,sPozY[rPoz])
		else
			--print("в пещерее никого нет")
		end
	end)
end