---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 12.05.2020 23:10
---
function StartTurretMoving(data)

	local AnotherWagon=FindUnitOfType(FourCC('o009'))
	SetUnitPathing(data.UnitHero,true)
	UnitCollisionOFF(data.UnitHero)
	BlzSetSpecialEffectYaw(data.TurretArrow,math.rad(0))

	TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
		local hero=data.UnitHero
		local x,y=GetUnitXY(AnotherWagon)
		SetUnitX(hero,x)
		SetUnitY(hero,y)
		SetUnitX(data.legs,x)
		SetUnitY(data.legs,y)
		SetUnitZ(data.legs,170)
		SetUnitZ(hero,170)
		UnitCollisionOFF(data.UnitHero)
		local imageX,imageY=GetUnitXY(hero)
		SetImagePosition(ConeImage,imageX-1280,imageY-1280/2,0)
		if data.ReleaseD then --момент выхода из тележки
			BlzSetSpecialEffectYaw(data.TurretArrow,math.rad(180))
			SetUnitX(hero,GetUnitX(hero)+50)
			DestroyTimer(GetExpiredTimer())
			data.EnterInTurret=false
			SetUnitZ(data.legs,0)
			SetUnitZ(hero,0)
		end
	end)


end