---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 12.05.2020 23:10
---
function StartTurretMoving(data)

	local AnotherWagon=FindUnitOfType(FourCC('o009'))
	--SetUnitPathing(data.UnitHero,true)
	--UnitCollisionOFF(data.UnitHero)
	BlzSetSpecialEffectYaw(data.TurretArrow,math.rad(0))
	BlzPauseUnitEx(data.UnitHero,true)
	ResetPeonAnimation(data.UnitHero)
	local isAttack=false
	TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
		local hero=data.UnitHero
		local x,y=GetUnitXY(AnotherWagon)
		SetUnitX(hero,x)
		SetUnitY(hero,y)
		SetUnitX(data.legs,x)
		SetUnitY(data.legs,y)
		SetUnitZ(data.legs,170)
		SetUnitZ(hero,170)
		local imageX,imageY=GetUnitXY(hero)
		SetImagePosition(ConeImage,imageX-1280/1.05,imageY-1280/2,0)
		--Стрельба
		local angle=data.LastTurn
		SetUnitFacing(data.Turret,angle)
		if data.ReleaseRMB and UnitAlive(data.UnitHero) then
			isAttack=true
			SingleCannon(hero,GetUnitFacing(data.Turret),"Bullets/Konstrukt_SubmachinegunMissile",1)
		else
			isAttack=false
		end

		if isAttack then
			SetUnitAnimation(data.Turret,"attack")
			SetUnitTimeScale(data.Turret,10)
		else
			SetUnitAnimation(data.Turret,"stand")
			SetUnitTimeScale(data.Turret,1)
		end


		if GetLocalPlayer()==GetOwningPlayer(hero) then
			ShowImage(ConeImage,true)
		end
		if data.ReleaseD then --момент выхода из тележки
			ShowImage(ConeImage,false)
			BlzSetSpecialEffectYaw(data.TurretArrow,math.rad(180))
			SetUnitX(hero,GetUnitX(hero)+50)
			DestroyTimer(GetExpiredTimer())
			data.EnterInTurret=false
			SetUnitZ(data.legs,0)
			SetUnitZ(hero,0)
		end
	end)


end