---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 23.01.2020 20:11
function InitUnitDeath()
	local gg_trg_DEADGUI = CreateTrigger()
	TriggerRegisterAnyUnitEventBJ(gg_trg_DEADGUI, EVENT_PLAYER_UNIT_DEATH)--меня полностью устраивает это событие
	TriggerAddAction(gg_trg_DEADGUI, function()
		local DeadUnit=GetTriggerUnit()--умерший

		local killer=GetKillingUnit()--убийца
		if IsUnitType(DeadUnit,UNIT_TYPE_HERO) then --герои


			TimerStart(CreateTimer(), 1, false, function()--юнит жив ещё 1 секунду
				local PD=GetOwningPlayer(DeadUnit)
				local pid=GetPlayerId(PD)
				local data=HERO[pid]
				data.Alive=false

			end)

			TimerStart(CreateTimer(), 5, false, function()
				local PD=GetOwningPlayer(DeadUnit)
				local pid=GetPlayerId(PD)
				local data=HERO[pid]
				data.Alive=true
				ReviveHero(DeadUnit,GetPlayerStartLocationX(PD),GetPlayerStartLocationY(PD),true)
				SelectUnitForPlayerSingle(DeadUnit,PD)
			end)
		end
		if IsUnitInGroup(DeadUnit,OrcSkeletonPoolG) then--зомбки орки с первой зоны
			OrcSkeletonPool[4]=OrcSkeletonPool[4]-1
			local hObelisk=GetUnitUserData(DeadUnit)
			for i=1,4 do
				if hObelisk==GetHandleId(OrcSkeletonPool[5+i]) then
					local obelisk=OrcSkeletonPool[5+i]
					SetUnitUserData(obelisk,GetUnitUserData(obelisk)-1)
				end
			end
		end
		if GetUnitTypeId(DeadUnit)==FourCC('h001') then
			ShowUnit(DeadUnit,false)
			DestroyEffect(AddSpecialEffect("Abilities\\Spells\\Undead\\AnimateDead\\AnimateDeadTarget.mdl",GetUnitXY(DeadUnit)))
		end
	end)
end
