---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 21.04.2020 21:03
function HeroEnterSaws()

	local FW={}
	FW[1]=CreateFogModifierRectBJ(false, Player(0), FOG_OF_WAR_VISIBLE, gg_rct_Saws)
	FW[2]=CreateFogModifierRectBJ(false, Player(1), FOG_OF_WAR_VISIBLE, gg_rct_Saws)
	FW[3]=CreateFogModifierRectBJ(false, Player(2), FOG_OF_WAR_VISIBLE, gg_rct_Saws)
	FW[4]=CreateFogModifierRectBJ(false, Player(3), FOG_OF_WAR_VISIBLE, gg_rct_Saws)

	local thisE = CreateTrigger()
	TriggerRegisterEnterRectSimple(thisE, gg_rct_Saws)
	TriggerAddAction(thisE, function()
		local hero=GetTriggerUnit()
		local pid=GetPlayerId(GetOwningPlayer(hero))
		--print("вошел в регион")
		FogModifierStart(FW[pid+1])
	end)

	local thisA = CreateTrigger()
	TriggerRegisterLeaveRectSimple(thisA, gg_rct_Saws)
	TriggerAddAction(thisA, function()
		local hero=GetTriggerUnit()
		local pid=GetPlayerId(GetOwningPlayer(hero))
		--print("вошел в регион")
		FogModifierStop(FW[pid+1])
	end)
end