---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 16.02.2020 18:42
---
function InitZone2()

	EnterArrow1()
end



function EnterArrow1()
	local ThisTrigger = CreateTrigger()
	local button=gg_dest_DTfx_1224
	TriggerRegisterEnterRectSimple(ThisTrigger, gg_rct_ActivateArrow1)
	TriggerAddAction(ThisTrigger, function()
		--print("смерть")
		--CreateArrow()
		KillDestructable(button)
		TimerStart(CreateTimer(),2,true, function ()
			DestructableRestoreLife(button, GetDestructableMaxLife(button), true)
			if PointContentUnit(GetDestructableX(button),GetDestructableY(button),200) then
				--print("Юнит втутри ")
				KillDestructable(button)
				--CreateArrow()
			else
				DestroyTimer(GetExpiredTimer())
				--print("Разрушение таймера ")
			end
		end)
	end)
end

function CreateArrow()
	print("Выпускаем стрелу")
end