---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 06.02.2020 12:47
---
function CreateAndForceBullet(hero,angle,speed,effectmodel,xs,ys)
	local xhero,yhero=GetUnitX(hero),GetUnitY(hero)
	local zhero=GetTerrainZ(xhero,yhero)+60
	local damage=BlzGetUnitBaseDamage(hero,0)/2
	if true then-- сдвиг только для ратлингов
		xs=MoveX(xs,20,angle-55)
		ys=MoveY(ys,20,angle-55)
	end
	local bullet=AddSpecialEffect(effectmodel,xs,ys)
	local bam=nil--AddSpecialEffect("Abilities/Weapons/SteamTank/SteamTankImpact.mdl",xs,ys)
	local cloud=nil--AddSpecialEffect("Abilities/Weapons/SteamTank/SteamTankImpact.mdl",xs,ys)
	local data=HERO[GetPlayerId(GetOwningPlayer(hero))]
	local CollisionEnemy=false
	local CollisisonDestr=false
	local ZPerepad=0
	BlzSetSpecialEffectYaw(bullet,math.rad(angle))

	--print("Скорость корабля"..data.CurrentSpeed)
	BlzSetSpecialEffectScale(bam,0.1)
	BlzSetSpecialEffectScale(cloud,0.02)
	DestroyEffect(bam)
	DestroyEffect(cloud)
	BlzSetSpecialEffectZ(bullet,zhero)
	--print(zhero)
	TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
		local x,y,z=BlzGetLocalSpecialEffectX(bullet),BlzGetLocalSpecialEffectY(bullet),BlzGetLocalSpecialEffectZ(bullet)
		local zGround=GetTerrainZ(MoveX(x,speed*2,angle),MoveY(y,speed*2,angle))
		BlzSetSpecialEffectPosition(bullet,MoveX(x,speed,angle),MoveY(y,speed,angle),z-2)
		BlzSetSpecialEffectPosition(cloud,MoveX(x,speed/3,angle),MoveY(y,speed/3,angle),z-2)
		local xbam,ybam=BlzGetLocalSpecialEffectX(bam),BlzGetLocalSpecialEffectY(bam)
		BlzSetSpecialEffectPosition(bam,MoveX(xbam,2*data.CurrentSpeed,GetUnitFacing(hero)),MoveY(ybam,2*data.CurrentSpeed,GetUnitFacing(hero)),z-50)
		--print("zGround ="..zGround.."z= "..z)
		--BlzSetSpecialEffectPosition(bam,MoveX(GetUnitX(hero),120,GetUnitFacing(hero)),MoveY(GetUnitY(hero),120,GetUnitFacing(hero)),z)
		ZPerepad=z-zGround
		--print(ZPerepad)
		CollisionEnemy=UnitDamageArea(hero,damage,x,y,50)
		CollisisonDestr=PointContentDestructable(x,y,100,false)
		if ZPerepad<=-10 or CollisionEnemy or CollisisonDestr then --or zGround+z>=-70+z

			PointContentDestructable(x,y,100,true)
			if z<=-90 then
				CreateTorrent(x,y)
				BlzSetSpecialEffectPosition(bullet,4000,4000,0)
			end

			UnitDamageArea(hero,damage,x,y,50)
			DestroyEffect(bullet)
			DestroyTimer(GetExpiredTimer())
		end
	end)
end
BulletEffect={
	"Abilities/Weapons/BoatMissile/BoatMissile.mdl",
	"Bullets/Bullet.mdl",
	"Bullets/Bullet1.mdl",
	"Bullets/HighSpeedProjectile_ByEpsilon.mdl",
	"Bullets/Incendiary Bullet Blue.mdl",
	"Bullets/Incendiary Bullet Orange.mdl",
	"Bullets/Incendiary Bullet Purple.mdl",
	"Bullets/Incendiary Bullet Green.mdl",
	"Bullets/Incendiary Bullet Red.mdl",--9
	"Bullets/Incendiary Bullet Yellow.mdl",
	"Bullets/Konstrukt_AssaultRifleMissile.mdl",
	"Bullets/Konstrukt_ShotgunMissile.mdl",
	"Bullets/Konstrukt_SubmachinegunMissile.mdl",
	"Bullets/ShotGunBullet.mdl",
	"Bullets/RifleMissileByEpsilon.mdl"
}

randomeffect=0--GetRandomInt(1,14)
function SingleCannon(hero)
	local angle=GetUnitFacing(hero)
	local x=MoveX(GetUnitX(hero),110,angle)
	local y=MoveY(GetUnitY(hero),110,angle)
	local data=
	CreateAndForceBullet(hero,angle,50,BulletEffect[3],x,y)
end
