---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 08.02.2020 12:24



function InitDamage()
	local DamageTrigger = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		TriggerRegisterPlayerUnitEvent(DamageTrigger, Player(i), EVENT_PLAYER_UNIT_DAMAGING) -- До вычета брони
		TriggerRegisterPlayerUnitEvent(DamageTrigger, Player(i), EVENT_PLAYER_UNIT_DAMAGED) -- После вычета брони
	end
	TriggerAddAction(DamageTrigger, function()
		local damage     = GetEventDamage() -- число урона
		local damageType = BlzGetEventDamageType()
		if damage < 1 then return end

		local eventId         = GetHandleId(GetTriggerEventId())
		local isEventDamaging = eventId == GetHandleId(EVENT_PLAYER_UNIT_DAMAGING)
		local isEventDamaged  = eventId == GetHandleId(EVENT_PLAYER_UNIT_DAMAGED)

		local target          = GetTriggerUnit() -- тот кто получил урон
		local targetHandleId  = GetHandleId(target)
		local caster          = GetEventDamageSource() -- тот кто нанёс урон
		local casterOwner     = GetOwningPlayer(caster)

		if isEventDamaged then
			if GetUnitTypeId(target)==FourCC('o002')  and GetOwningPlayer(target)==Player(10) then --урон по кодою
				--print("урон по кодою")
				local x,y=GetUnitXY()
				BlzSetEventDamage(0)
				local endX,endY=GetRectCenterX(gg_rct_KodoZone),GetRectCenterY(gg_rct_KodoZone)
				IssuePointOrder(target,"move",endX,endY)
				if IsUnitInRangeXY(target,endX,endY,120) then
					SetUnitOwner(target,casterOwner,true)
					--print("Ачивка кодоя")
					local data=HERO[GetPlayerId(casterOwner)]
					data.KodoCount=data.KodoCount+1-- считаем бездействие
					if not data.Perk8 then
						if data.KodoCount>=1 then
							data.Perk8=true
							BlzSetUnitArmor(caster,BlzGetUnitArmor(caster)+10)
							if GetLocalPlayer()==casterOwner then
								BlzFrameSetVisible(PerkIsLock[8],false)
							end
							print("Рабочий поднял бунт")
							--Allian
						end
					end
					--Старт ИИ кодоя
					TimerStart(CreateTimer(), 10, true, function()
						if not UnitAlive(target) then DestroyTimer(GetExpiredTimer()) end
						if GetUnitCurrentOrder(target)~=String2OrderIdBJ("move") then
							local rx,ry=GetRandomInt(-500,500),GetRandomInt(-500,500)
							IssuePointOrder(target,"move", rx,ry)
						end
					end)
					TimerStart(CreateTimer(), 1, true, function()
						if not UnitAlive(target) then DestroyTimer(GetExpiredTimer()) end
						local e=nil
						GroupEnumUnitsInRange(perebor,GetUnitX(target),GetUnitY(target),600,nil)
						while true do
							e = FirstOfGroup(perebor)

							if e == nil then break end
							if UnitAlive(e) and IsUnitEnemy(e,GetOwningPlayer(target)) then
								--print("пытаемся скушать врага")
								--if Cast(target,0,0,e) then
								if IssueTargetOrder(target,"devour",e) then
									--print("успешно")
								else

								end
							end
							GroupRemoveUnit(perebor,e)
						end
					end)
				end
				TimerStart(CreateTimer(), 2, false, function()
					IssueImmediateOrder(target,"stop")
				end)

			end
		end
	end)
end




perebor=CreateGroup()
function UnitDamageArea(u,damage,x,y,range,ZDamageSource,EffectModel)
	local OnlyCHK=false
	local isdamage=false
	local e=nil
	local hero=nil
	if ZDamageSource==nil then ZDamageSource=GetUnitZ(u)+60 end
	--print("Поиск целей в на высоте "..ZDamageSource)
	GroupEnumUnitsInRange(perebor,x,y,range,nil)
	while true do
		e = FirstOfGroup(perebor)
		if e == nil then break end
		if UnitAlive(e) and IsUnitEnemy(e,GetOwningPlayer(u))  and IsUnitZCollision(e,ZDamageSource) then

			UnitDamageTarget( u, e, damage, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_NORMAL, WEAPON_TYPE_WHOKNOWS )
			isdamage=true
			hero=e
			if EffectModel~=nil then
				--print("эффеет")
				local DE=AddSpecialEffect(EffectModel,GetUnitX(e),GetUnitY(e))
				BlzSetSpecialEffectZ(DE,ZDamageSource)
				DestroyEffect(DE)
			end
			if IsUnitType(u,UNIT_TYPE_HERO) then
				local data=HERO[GetPlayerId(GetOwningPlayer(u))]
				if data.Perk6 then -- удар тора
					--print("удар тора")
					CastArea(u,FourCC('A003'),x,y)
				end
			end
		end
		--ремонт
		if true and UnitAlive(e) and IsUnitAlly(e,GetOwningPlayer(u)) and IsUnitZCollision(e,ZDamageSource) and IsUnitType(e,UNIT_TYPE_STRUCTURE) then
			local data=HERO[GetPlayerId(GetOwningPlayer(u))]
			--print("лечим")
			local heal=HealUnit(e,BlzGetUnitBaseDamage(u,0))
			data.Repairs=data.Repairs+heal
			data.RevoltSec=0
			if not data.Perk6 then
				if data.Repairs>=1000 then
					data.Perk6=true
					if GetLocalPlayer()==GetOwningPlayer(u) then
						BlzFrameSetVisible(PerkIsLock[6],false)
					end
				end
			end
		end
		GroupRemoveUnit(perebor,e)
	end
	if PointContentDestructable(x,y,range,true,1+damage/4,u) then	isdamage=true	end
	return isdamage, hero
end

function IsUnitZCollision(hero,ZDamageSource)
	local zcollision=false
	local z=GetUnitZ(hero)

	if  ZDamageSource+60>=z and ZDamageSource-60<=z then
		zcollision=true
	else
		--print("Высота снаряда="..ZDamageSource.."Высота юнита="..z)
	end
	return zcollision
end


function UnitDamageLine(u,damage,x,y,range,distance,angle,z)
	local isdamage=false
	local nx,ny
	for i=0,distance/range do
		nx=MoveX(x,i*range,angle)
		ny=MoveY(y,i*range,angle)
		UnitDamageArea(u,damage,nx,ny,range,z)
	end
	return isdamage
end

function UnitRocketArea(hero,x,y,range)
	local find=false
	local e--временный юнит
	local targ=nil
	--print("стреляем")
	GroupEnumUnitsInRange(perebor,x,y,range,nil)
	while true do
		e = FirstOfGroup(perebor)
		if e == nil or find==true then break end
		if UnitAlive(e) and IsUnitEnemy(e,GetOwningPlayer(hero)) then
			targ=e
		end
		GroupRemoveUnit(perebor,e)
	end
	local dummy=CreateUnit(GetOwningPlayer(hero), DummyID, GetUnitX(hero), GetUnitY(hero), 0)
	SetUnitZ(dummy,GetUnitZ(hero))
	UnitAddAbility(dummy,FourCC('A003'))
	UnitApplyTimedLife(dummy,DummyID,1)
	if targ~=nil then
		--print("цель определена- "..GetUnitName(targ))
		Cast(dummy,0,0,targ)
	else
		targ=CreateUnit(Player(PLAYER_NEUTRAL_AGGRESSIVE), DummyID, x, y, 0)

		UnitRemoveAbility(targ,FourCC('Aloc'))
		if Cast(dummy,0,0,targ)==false then
			--print("выстрел в пустоту")
			HeroUpdateWeaponCharges(hero,3,-1)
		end
		UnitApplyTimedLife(targ,DummyID,3)
		--print("Нет врагов, летим в воду")
	end
end