---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 19.04.2020 17:39
function LeavePlayer()
	local this = CreateTrigger()
	TriggerRegisterPlayerEventLeave(this, Player(0))
	TriggerRegisterPlayerEventLeave(this, Player(1))
	TriggerRegisterPlayerEventLeave(this, Player(2))
	TriggerRegisterPlayerEventLeave(this, Player(3))

	TriggerAddAction(this, function()
		local p=GetTriggerPlayer()
		--print("Разумом "..GetPlayerName(p).." овладел ИИ")
		if BlzGetLocale()=="ruRU" then
			print("|cff8080ffСистема: |r".."Разумом "..GetPlayerName(p).." овладел ИИ")
		else
			print("|cff8080ffSystem: |r"..GetPlayerName(p).." Lose control")
		end
		local data=HERO[GetPlayerId(p)]
		data.PlayerIsLeave=true
		StartPeonAI(data.UnitHero)
	end)
end