---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 11.05.2020 9:42
---

function CreateLocalImages()
	for i=0,3 do
		local data=HERO[i]
		data.CircleImage=CreateImage("circ.blp",128,128,128,4000,4000,0,0,0,0,4)
		SetImageRenderAlways(data.CircleImage, true)
		ShowImage(data.CircleImage,false)
	end
end