---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 21.02.2020 20:39

function Enter00()
	local trg_InCombatZone = CreateTrigger()
	TriggerRegisterEnterRectSimple(trg_InCombatZone, gg_rct_Combat0Zone)
	TriggerAddAction(trg_InCombatZone, function ()
		local x,y=GetRectCenterX(gg_rct_Combat0Zone),GetRectCenterY(gg_rct_Combat0Zone)
		local temp=CreateGroup()
		--print("вошел в зону боя")
		DisableTrigger(GetTriggeringTrigger())
		for i=1, 3 do
			local new=CreateUnit(Player(11), FourCC('u000'), x, y, 0)
			StartSheepAI(new)
			GroupAddUnit(temp,new)
		end
		TimerStart(CreateTimer(), 1, true, function()
			if IsUnitGroupDeadBJ(temp) then
				DestroyTimer(GetExpiredTimer())
				DestroyGroup(temp)
				--print("мертвы, открываем ворота")
				QuestMessageBJ(GetPlayersAllies(Player(0)), bj_QUESTMESSAGE_UNITAVAILABLE, "|cffffff00Враги уничтожены:|r путь свободен")
				EnumDestructablesInRectAll(gg_rct_Zone02In, function()
					KillDestructable(GetEnumDestructable())
				end)
				EnumDestructablesInRectAll(gg_rct_Zone02Out, function()
					KillDestructable(GetEnumDestructable())
				end)
			end
		end)
	end)
end