---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 23.02.2020 20:49

function InMineWay()
	local gg_trg_InMineWay = CreateTrigger()
	TriggerRegisterEnterRectSimple(gg_trg_InMineWay, gg_rct_Zone03In)
	TriggerAddAction(gg_trg_InMineWay, function()
		print("баржа отправляется в путь")
		DisableTrigger(GetTriggeringTrigger())
		local barga=FindUnitOfType(FourCC('o001'),1000,GetUnitXY(GetTriggerUnit()))
		UnitAddAbility(barga,FourCC('Avul'))
		local xs,ys=GetUnitXY(barga)
		local x,y=GetRectCenterX(gg_rct_Zone03Out),GetRectCenterY(gg_rct_Zone03Out)
		IssuePointOrder(barga,"move",x,y)
		TimerStart(CreateTimer(), 1, true, function()
			if GetUnitCurrentOrder(barga)==0 then
				IssuePointOrder(barga,"move",x,y)
			end
			if GetUnitCurrentOrder(barga)~=String2OrderIdBJ("move") then
				--print("остановка "..GetUnitCurrentOrder(barga)..OrderId2String(GetUnitCurrentOrder(barga)))
			end
			--print("Созданамина")
			CreateBarrel(barga,GetUnitFacing(barga)-180,100)
			if IsUnitInRangeXY(barga,x,y,250)  then
				if GetDestructableLife(gg_dest_B000_0131) <= 0 then
					--print("конец")
					DestroyTimer(GetExpiredTimer())
				end
				IssuePointOrder(barga,"move",xs,ys)
				--print("назад")
			end
			if IsUnitInRangeXY(barga,xs,ys,200) then
				--print("вперёд")
				IssuePointOrder(barga,"move",x,y)
			end
		end)
	end)
end