---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 10.01.2020 22:05
--
---Глобалки
TIMER_PERIOD = 0.03125
HERO={}
do
	local InitGlobalsOrigin = InitGlobals -- записываем InitGlobals в переменную
	function InitGlobals()
		InitGlobalsOrigin() -- вызываем оригинальную InitGlobals из переменной
		InitGameCore()
		--hideEverything()
		InitMouseMoveTrigger()
		InitDamage()
	end

end

function InitGameCore()
	--создаём героев
	--BlzEnableSelections(false,false)
	EnableDragSelect(false,false)
	HERO[0]={
		ReleaseW=false,
		ReleaseS=false,
		ReleaseA=false,
		ReleaseD=false,
		Acceleration=0,
		ReleaseLMB=false,
		ReleaseRMB=false,
		SpeedBase=9,
		UnitHero=CreateUnit(Player(0), FourCC('H000'), GetPlayerStartLocationX(Player(0)), GetPlayerStartLocationY(Player(0)), 0),
		CurrentSpeed=0,
		WeaponIndex=1,
		AngleForce=0, --типа какой-то уго для отталкивания
		IsDisabled=false,
		pid=0,
		--legs=AddSpecialEffect("legs",0,0),
		legs=CreateUnit(Player(0), FourCC('o000'), GetPlayerStartLocationX(Player(0)), GetPlayerStartLocationY(Player(0)), 0),
		isattack=false,
		AttackTime=0
		--Camera=CreateUnit(Player(0), FourCC('e001'), GetPlayerStartLocationX(Player(0)), GetPlayerStartLocationY(Player(0)), 0)
	}


	-----------------------------------------------------------------OSKEY_W
	local gg_trg_EventUpW = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(gg_trg_EventUpW,Player(i),OSKEY_W,0,true)
	end
	TriggerAddAction(gg_trg_EventUpW, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.ReleaseW=true
		SetUnitAnimationByIndex(data.legs,16)
	end)
	local TrigDepressW = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigDepressW,Player(i),OSKEY_W,0,false)
	end
	TriggerAddAction(TrigDepressW, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.ReleaseW=false
	end)
	-----------------------------------------------------------------OSKEY_S
	local gg_trg_EventUpS = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(gg_trg_EventUpS,Player(i),OSKEY_S,0,true)
	end
	TriggerAddAction(gg_trg_EventUpS, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.ReleaseS=true
		SetUnitAnimationByIndex(data.legs,16)
	end)
	local TrigDepressS = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigDepressS,Player(i),OSKEY_S,0,false)
	end
	TriggerAddAction(TrigDepressS, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.ReleaseS=false
	end)
	-----------------------------------------------------------------OSKEY_D
	local TrigPressD = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigPressD,Player(i),OSKEY_D,0,true)
	end
	TriggerAddAction(TrigPressD, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.ReleaseD=true
		SetUnitAnimationByIndex(data.legs,16)
	end)
	local TrigDePressD = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigDePressD,Player(i),OSKEY_D,0,false)
	end
	TriggerAddAction(TrigDePressD, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.ReleaseD=false
	end)
	-----------------------------------------------------------------OSKEY_A
	local TrigPressA = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigPressA,Player(i),OSKEY_A,0,true)
	end
	TriggerAddAction(TrigPressA, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.ReleaseA=true
		SetUnitAnimationByIndex(data.legs,16)
	end)
	local TrigDePressA = CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		BlzTriggerRegisterPlayerKeyEvent(TrigDePressA,Player(i),OSKEY_A,0,false)
	end
	TriggerAddAction(TrigDePressA, function()
		local pid=GetPlayerId(GetTriggerPlayer())
		local data=HERO[pid]
		data.ReleaseA=false
	end)
	-----------------------------------------------------------------LMB
	local TrigPressLMB=CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		TriggerRegisterPlayerEvent(TrigPressLMB, Player(i), EVENT_PLAYER_MOUSE_DOWN)
	end
	TriggerAddAction(TrigPressLMB, function()
		--print("any")
		if BlzGetTriggerPlayerMouseButton() == MOUSE_BUTTON_TYPE_LEFT then
			local pid=GetPlayerId(GetTriggerPlayer())
			local data=HERO[pid]
			data.ReleaseLMB=true
			local hero=data.UnitHero
		end
	end)
	local TrigDePressLMB=CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		TriggerRegisterPlayerEvent(TrigDePressLMB, Player(i), EVENT_PLAYER_MOUSE_UP)
	end

	TriggerAddAction(TrigDePressLMB, function()
		--print("any")
		if BlzGetTriggerPlayerMouseButton() == MOUSE_BUTTON_TYPE_LEFT then
			local pid=GetPlayerId(GetTriggerPlayer())
			local data=HERO[pid]
			data.ReleaseLMB=false
		end
	end)
	-----------------------------------------------------------------RMB
	local TrigPressRMB=CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		TriggerRegisterPlayerEvent(TrigPressRMB, Player(i), EVENT_PLAYER_MOUSE_DOWN)
	end
	TriggerAddAction(TrigPressRMB, function()
		--print("any")
		if BlzGetTriggerPlayerMouseButton() == MOUSE_BUTTON_TYPE_RIGHT then
			local pid=GetPlayerId(GetTriggerPlayer())
			local data=HERO[pid]
			data.ReleaseRMB=true
			local hero=data.UnitHero
			data.AttackTime=0.7
			randomeffect=GetRandomInt(1,15)
			--print("Случайное оружие №-"..randomeffect)
			--data.isattack=true
			--SetUnitAnimationByIndex(hero,14)
			--SingleCannon(hero)
		end
	end)
	local TrigDePressRMB=CreateTrigger()
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		local player = Player(i)
		TriggerRegisterPlayerEvent(TrigDePressRMB, Player(i), EVENT_PLAYER_MOUSE_UP)
	end
	TriggerAddAction(TrigDePressRMB, function()
		--print("any")
		if BlzGetTriggerPlayerMouseButton() == MOUSE_BUTTON_TYPE_RIGHT then
			local pid=GetPlayerId(GetTriggerPlayer())
			local data=HERO[pid]
			data.ReleaseRMB=false
			--SetUnitAnimation(data.UnitHero,"Stand")
			--data.isattack=false
		end
	end)

	-----------------------------------------------------------------Lock
	TimerStart(CreateTimer(), 0.01, true, function()
		local data=HERO[0]
		local hero=data.UnitHero
		ForceUIKeyBJ(GetOwningPlayer(hero),"M")
		IssueImmediateOrder(hero,"stop")
	end)

------------------------------ТЕСТ АНИМАЦИЙ
	local ai=0
	TimerStart(CreateTimer(), 2, true, function()
		local data=HERO[0]
		--local hero=data.legs--UnitHero
		SetUnitAnimationByIndex(hero,ai)
		--print(ai)
		ai=ai+1
	end)



	local sec=0
	local sec2=0
	--local secattack=0
	TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
		for _, data in pairs(HERO) do
			local hero= data.UnitHero
			local id=data.pid
			local p=GetOwningPlayer(hero)
			local angle=0
			local speed=data.SpeedBase
			local x,y=GetUnitXY(hero)
			local IiMoving=false
			local walk=false
			local startwalk=false
			local standanim=false
			local walkattack=false
			local turn=AngleBetweenXY(x,y,GetPlayerMouseX[id],GetPlayerMouseY[id])/bj_DEGTORAD
			local aSpeed=0.7


			--Синхронизация ног
			SetUnitX(data.legs,x)
			SetUnitY(data.legs,y)
			SetUnitFacing(hero,turn)



			sec=sec+TIMER_PERIOD
			if sec>=1 then
				sec=0
				walk=true
				standanim=true

			end

			sec2=sec2+TIMER_PERIOD
			if sec2>=1 then
				sec2=0
				walkattack=true
			end





			data.AttackTime=data.AttackTime+TIMER_PERIOD
			if data.AttackTime>=aSpeed then
				data.AttackTime=0
				if data.ReleaseRMB then
					data.isattack=true
					print("time attack")
					--SingleCannon(hero)
				end
			end


			if data.ReleaseW and data.ReleaseD==false and data.ReleaseA==false then
				--print("only w")
				angle=90
				IiMoving=true
			end
			if data.ReleaseW and data.ReleaseD then
				--print("w+d")
				angle=90-45
				IiMoving=true
			end
			if data.ReleaseW and data.ReleaseA then
				--print("w+s")
				angle=90+45
				IiMoving=true
			end


			if data.ReleaseS and data.ReleaseD==false and data.ReleaseA==false then
				angle=270
				IiMoving=true
			end
			if data.ReleaseS and data.ReleaseD  then
				angle=270+45
				IiMoving=true
			end
			if data.ReleaseS and data.ReleaseA  then
				angle=270-45
				IiMoving=true
			end


			if data.ReleaseD and data.ReleaseW==false and data.ReleaseS==false then
				angle=0
			    IiMoving=true
			end

			if data.ReleaseA and data.ReleaseW==false and data.ReleaseS==false then
				angle=180
				IiMoving=true
			end

			if turn<0 and turn>-180 then
				--print("проблемная область")
				turn=turn+360
			end
			--print("угол движения="..angle.." угол поворота="..turn)

			local dif=100
			if angle+dif>turn and angle-dif<turn then
				--print("по направлению "..angle)
				SetUnitTurnSpeed(data.legs,1)
			else
				--print("движение спиной"..turn)
				SetUnitTurnSpeed(data.legs,-1)
			end


			if IiMoving then
				if startwalk==false then
					sec=1
					startwalk=true
				end
				if data.isattack==false then
					if walkattack then
						--walkattack=false
						if data.ReleaseRMB==false then
						--	print("reset in walk")
							SetUnitAnimation(hero,"Stand")
						end
					end
				end


				if walk and walkattack then
					--BlzPlaySpecialEffect(data.legs,ANIM_TYPE_WALK)

					--BlzSetSpecialEffectYaw(data.legs,math.rad(angle))
					BlzSetUnitFacingEx(data.legs,angle)
					SetUnitAnimationByIndex(data.legs,16)
					walk=false
					--print("перебирай ногами"..GetUnitName(data.legs))
				end
				------------------------------Движение
				local newX,newY=MoveX(x,speed,angle),MoveY(y,speed,angle)
				SetUnitPositionSmooth(hero,newX,newY)
			else--не двигается
				if standanim then
					--BlzPlaySpecialEffect(data.legs,ANIM_TYPE_STAND)
					--SetUnitAnimation(data.legs,"stand")
					SetUnitAnimationByIndex(data.legs,11)
					--print("stand")
				end
				startwalk=false
				--BlzSetSpecialEffectYaw(data.legs,math.rad(turn))
				BlzSetUnitFacingEx(data.legs,turn)
				--SetUnitAnimation(hero,"Stand") --14
				--print("1")
			end

			if data.isattack then
				walkattack=false
				SetUnitAnimationByIndex(hero,7) --проигрываем анимацию атаки
				--print("play attack")
				data.isattack=false
			else
				if standanim then
					standanim=false
					if IiMoving==false and data.ReleaseRMB==false then
						--print("reset any")
						--SetUnitAnimation(hero,"Stand")
						SetUnitAnimationByIndex(hero,11)
					end
				end
			end
			---дополнительный сборс
			if data.ReleaseRMB==false and data.isattack==false and IiMoving then
				if IiMoving then
					if walkattack then
						walkattack=false
						SetUnitAnimationByIndex(hero,16) --анимация движения без атаки
						--print("шевели поршнями реже")
					end
				else
					print("total reset")
					SetUnitAnimation(hero,"Stand")
				end
			end
		end
	end)
end


