---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 05.04.2020 18:56
function WaveAttack()
	local new
	local x,y=0,0
	local loc=nil
	TimerStart(CreateTimer(), 60, true, function() --волки
		x,y=GetRectCenterX(gg_rct_WalkSpawnZone),GetRectCenterY(gg_rct_WalkSpawnZone)
		new=CreateUnit(Player(10), FourCC('n000'), x, y, 0)
		IssuePointOrder(new,"attack",0,0)
	end)
	TimerStart(CreateTimer(), 70, true, function() --энты
		loc =GetRandomLocInRect(gg_rct_TrentZone)

		x,y=GetLocationX(loc),GetLocationY(loc)
		--print("энт "..x)
		new=CreateUnit(Player(10), FourCC('e001'), x, y, 0)
		IssuePointOrder(new,"attack",0,0)
	end)
	TimerStart(CreateTimer(), 80, true, function() -- камни
		loc =GetRandomLocInRect(gg_rct_StoneZoneS)
		x,y=GetLocationX(loc),GetLocationY(loc)
		new=CreateUnit(Player(10), FourCC('n002'), x, y, 0)
		IssuePointOrder(new,"attack",0,0)
	end)
	TimerStart(CreateTimer(), 90, true, function() --лава
		loc =GetRandomLocInRect(gg_rct_Lava)
		x,y=GetLocationX(loc),GetLocationY(loc)
		new=CreateUnit(Player(10), FourCC('n004'), x, y, 0)
		IssuePointOrder(new,"attack",0,0)
	end)
	TimerStart(CreateTimer(), 50, true, function() --люди
		loc =GetRandomLocInRect(gg_rct_Workers)
		x,y=GetLocationX(loc),GetLocationY(loc)
		new=CreateUnit(Player(10), FourCC('hpea'), x, y, 0)
		IssuePointOrder(new,"attack",0,0)
	end)
	TimerStart(CreateTimer(), 60, true, function() --овцы
		loc =GetRandomLocInRect(gg_rct_SheepZone)
		x,y=GetLocationX(loc),GetLocationY(loc)
		new=CreateUnit(Player(10), FourCC('n001'), x, y, 0)
		AnyData[GetHandleId(new)]={
			x=GetUnitX(new),
			y=GetUnitY(new),
		}
		IssuePointOrder(new,"move",0,0)
	end)
	--RemoveLocation(loc)
end