---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 05.04.2020 18:56
function WaveAttack(delay)
	local new
	local x,y=0,0
	local loc=nil
	local OrkStove=FindUnitOfType(FourCC('o001'))
	TimerStart(CreateTimer(), 60+delay, true, function() --волки
		x,y=GetRectCenterX(gg_rct_WalkSpawnZone),GetRectCenterY(gg_rct_WalkSpawnZone)
		new=CreateUnit(Player(10), FourCC('n000'), x, y, 0)
		IssuePointOrder(new,"attack",0,0)
	end)
	TimerStart(CreateTimer(), 70+delay, true, function() --энты
		loc =GetRandomLocInRect(gg_rct_TrentZone)

		x,y=GetLocationX(loc),GetLocationY(loc)
		--print("энт "..x)
		new=CreateUnit(Player(10), FourCC('e001'), x, y, 0)
		IssuePointOrder(new,"attack",0,0)
	end)
	TimerStart(CreateTimer(), 80+delay, true, function() -- камни големы
		loc =GetRandomLocInRect(gg_rct_StoneZoneS)
		x,y=GetLocationX(loc),GetLocationY(loc)
		new=CreateUnit(Player(10), FourCC('n002'), x, y, 0)
		IssuePointOrder(new,"attack",0,0)
	end)
	TimerStart(CreateTimer(), 90+delay, true, function() --лава
		loc =GetRandomLocInRect(gg_rct_Lava)
		x,y=GetLocationX(loc),GetLocationY(loc)
		new=CreateUnit(Player(10), FourCC('n004'), x, y, 0)
		IssuePointOrder(new,"attack",0,0)
	end)
	TimerStart(CreateTimer(), 50+delay, true, function() --люди
		loc =GetRandomLocInRect(gg_rct_Workers)
		x,y=GetLocationX(loc),GetLocationY(loc)
		new=CreateUnit(Player(10), FourCC('hpea'), x, y, 0)
		IssuePointOrder(new,"attack",0,0)
	end)
	TimerStart(CreateTimer(), 60+delay, true, function() --овцы
		loc =GetRandomLocInRect(gg_rct_SheepZone)
		x,y=GetLocationX(loc),GetLocationY(loc)
		new=CreateUnit(Player(10), FourCC('n001'), x, y, 0)
		AnyData[GetHandleId(new)]={
			x=GetUnitX(new),
			y=GetUnitY(new),
		}
		IssuePointOrder(new,"move",0,0)
	end)
	TimerStart(CreateTimer(), 90+delay, true, function() --мурлоки
		loc =GetRandomLocInRect(gg_rct_Morlok)
		x,y=GetLocationX(loc),GetLocationY(loc)
		for _=1,GetRandomInt(1,3) do
			new=CreateUnit(Player(11), FourCC('n005'), x, y, 0)
			IssueTargetOrder(new,"attack",OrkStove)
		end
	end)
	--RemoveLocation(loc)
end
