---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 04.05.2020 2:22
---
function InitCDSystem()
	if not BlzLoadTOCFile("war3mapimported\\mybar.toc") then
			print("warning")
	end
end


function StartFrameCD(cd,data,index)
	local amount=5/cd

	local fh=data.ReloadIco[index]

	if not fh then
		print("error Не могу перезарядить фрейм, так как его нет")
		return

	end

	local full=0


	TimerStart(CreateTimer(), 0.05, true, function()
		full=full+amount
		BlzFrameSetValue(fh, full)
		if full>=100 then
			DestroyTimer(GetExpiredTimer())
			full=0
		end
	end)

end
