---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 04.05.2020 2:22
---



function Trig_Nahkampf_Initialisierung_Actions ()
	if not BlzLoadTOCFile("war3mapimported\\mybar.toc") then
		print("warning")
	end
	local fh = BlzCreateSimpleFrame("MyBar", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 0)
	BlzFrameSetAbsPoint(fh, FRAMEPOINT_CENTER, 0.4, 0.3)
	BlzFrameSetValue(fh, 50)
	BlzFrameSetText(BlzGetFrameByName("MyBarText", 0), "")
	BlzFrameSetTexture(BlzGetFrameByName("MyBarBackground", 0), "Replaceabletextures\\CommandButtons\\BTNHeroDeathKnight.blp", 0, true)
	BlzFrameSetTexture(fh, "Replaceabletextures\\CommandButtons\\BTNArthas.blp", 0, true)
	BlzFrameSetSize(fh, 0.08, 0.08)

	TimerStart(CreateTimer(), 0.08, true, function()
		BlzFrameSetValue(fh, BlzFrameGetValue(fh) + GetRandomReal(-3, 3))
	end)

end
