---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 27.04.2020 20:07
function AddQuest(compas,hero,qx,qy,questendunit)
	local x,y=GetUnitX(hero),GetUnitY(hero)
	local model="AneuCaster"
	local player=GetOwningPlayer(hero)
	local data=HERO[GetPlayerId(player)]

	if GetLocalPlayer()~=player then
		model=""
	else
		--print("звук созданного квеста")
		StartSound(bj_questSecretSound)
	end
	local QuestPointer=AddSpecialEffect(model,x,y)
	BlzSetSpecialEffectPitch(QuestPointer,math.rad(-90))--/bj_DEGTORAD

	if compas==true then
		data.Compass=QuestPointer
		data.CompassX,data.CompassY=qx,qy
	end
end
